/obj/item/storage/backpack/satchel/flat/prison/PopulateContents()
	new /obj/item/screwdriver(src)
	new /obj/item/radio(src)
	new /obj/item/assembly/signaler(src)
	new /obj/item/assembly/signaler(src)
